// packages/@vue/components/PivotTable.vue
<script setup lang="js">
import { computed } from 'vue'
import PivotData from '../../@core/js/PivotData'
// import { TableRenderer, TSVRenderer, FoobarRenderer, TestRenderer } from './renderers'

const props = defineProps(
  // ...PivotData.defaultProps,
  {
    data: {
      type: Array,
      default: () => [],
    },
    rendererName: {
      type: String,
    },
    // renderers: {...TableRenderer, ...TSVRenderer, ...FoobarRenderer},
    // renderers: { ...TableRenderer, ...FoobarRenderer, ...TestRenderer },
    renderers: {
      type: Object,
      default: () => ({
        Table: TableRenderer,
        Foobar: FoobarRenderer,
        Test: TestRenderer
      })
    },
  }
)

const renderer = computed(() => {
  const rendererName = props.rendererName
  return props.renderers[rendererName] || Object.values(props.renderers)[0]
})
console.log('JB :: ', props.data)
</script>

<template>
  <Component :is="renderer" v-bind="props" />
</template>

// packages/@react/components/PivotTable.jsx
import React from 'react'
import PropTypes from 'prop-types'
import PivotData from '../../@core/js/PivotData'
import { TableRenderer, TSVRenderer, FoobarRenderer, TestRenderer } from './renderers'

/* eslint-disable react/prop-types */
// eslint can't see inherited propTypes!

class PivotTable extends React.PureComponent {
  render() {
    const Renderer = this.props.renderers[
      this.props.rendererName in this.props.renderers
        ? this.props.rendererName
        : Object.keys(this.props.renderers)[0]
    ]

    return <Renderer {...this.props} />
  }
}

PivotTable.propTypes = {
  ...PivotData.propTypes,
  rendererName: PropTypes.string,
  renderers: PropTypes.objectOf(PropTypes.func),
}

PivotTable.defaultProps = {
  ...PivotData.defaultProps,
  rendererName: 'Table',
  // renderers: {...TableRenderer, ...TSVRenderer, ...FoobarRenderer},
  renderers: { ...TableRenderer, ...FoobarRenderer, ...TestRenderer },
}

export default PivotTable
