// apps/data-explorer.react/src/App.jsx
import { useState, useEffect } from 'react'
import PropTypes from 'prop-types'
import PivotTableUI from '../../../packages/@react'
import { TSVRenderer, createPlotlyRenderer, createChartjsRenderer}  from '../../../packages/@react/components/renderers'
// import {aggregators, aggregatorTemplates }  from '../../../packages/@core/js/aggregators'
import { getData } from '../../../common/js/services/dataService'
import {isEmptyObject}  from '../../../common/js/utility'
import STATIC, { colors as palette  } from '../../../common/js/constants'

import Plotly from 'plotly.js/dist/plotly'
import createPlotlyComponent from 'react-plotly.js/factory'
// import Plot from 'react-plotly.js'

import { Chart as ChartJS, Tooltip, Legend, CategoryScale, LinearScale, BarElement, BarController } from 'chart.js'
import { Bar } from 'react-chartjs-2'

ChartJS.register(Tooltip, Legend, CategoryScale, LinearScale, BarElement, BarController)
const PlotlyInstance = createPlotlyComponent(Plotly) // JB: create instance of Plotly

import './app.css'

const chartjsData = {
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [
    {
      label: 'Dataset 1',
      data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: 'rgba(255, 99, 132, 0.5)',
    },
    {
      label: 'Dataset 2',
      data: [200, 300, 400, 500, 600, 700, 800],
      backgroundColor: 'rgba(53, 162, 235, 0.5)',
    },
  ],
};

const chatjsOptions = {
  responsive: true,
  indexAxis: 'y',
  plugins: {
    legend: {
      position: 'top',
    },
    title: {
      display: false,
    },
    tooltip: {
      callbacks: {
        title: () => null
      },
    },
    usePointStyle: true,
  },
}

// const options = {
// 	aggregatorName: STATIC.AGGREGATOR.uniqueCountOfGrandTotal,
// 	unusedOrientationCutoff: Infinity,
// }

export default function App({
	uid = '',
}) {
	const [dataset, setDataset] = useState([])

	const [questionFilters, setQuestionFilters] = useState([])

	const [keyVariablesFilters, setKeyVariablesFilters] = useState([])

	const [activeRenderer, setActiveRenderer] = useState(STATIC.RENDERER.table)

	useEffect(() => {
		async function load() {
			try {
        const data = await getData(uid)
				setDataset(data)
			} catch (error) {
				console.log('Something went wrong retrieving the data from the endpoint :: ', error)
			}
		}		

		load()
	}, [uid])

	return (
    <section className="pivot-table">
      <PivotTableUI
        data={dataset} // REQUIRED - everything else is optional
        renderers={{
					...TSVRenderer,
					// ...createPlotlyRenderer(Plot, {}), // JB: Using react-plotly.js
					...createPlotlyRenderer(PlotlyInstance, {}),
    			...createChartjsRenderer(Bar, { palette }),
        }}
        // aggregators={{
        // 	...aggregators,
        // }}

        cols={['Party Size']}
        rows={['Payer Gender']}
        rendererName={activeRenderer}

        // {...options}
      />
    </section>
	)
}

App.propTypes = {
	uid: PropTypes.string.isRequired,
}

// apps/data-explorer.vue/src/App.vue
<script setup lang="js">
import { ref, onMounted } from 'vue'
import PivotTableUI from '../../../packages/@vue'
import { TSVRenderer, createPlotlyRenderer, createChartjsRenderer } from '../../../packages/@vue/components/renderers'
import { getData } from '../../../common/js/services/dataService'
import STATIC, { colors as palette  } from '../../../common/js/constants'

// import { Plotly } from '@aurium/vue-plotly'
import Plotly from '@aurium/vue-plotly'

import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale } from 'chart.js'
import { Bar } from 'vue-chartjs'

ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale)

const chartjsData = {
  labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
  datasets: [
    {
      label: 'Dataset 1',
      data: [100, 200, 300, 400, 500, 600, 700],
      backgroundColor: 'rgba(255, 99, 132, 0.5)',
    },
    {
      label: 'Dataset 2',
      data: [200, 300, 400, 500, 600, 700, 800],
      backgroundColor: 'rgba(53, 162, 235, 0.5)',
    },
  ],
};

const chatjsOptions = {
  responsive: true,
  indexAxis: 'y',
  plugins: {
    legend: {
      position: 'top',
    },
    title: {
      display: false,
    },
    tooltip: {
      callbacks: {
        title: () => null
      },
    },
    usePointStyle: true,
  },
}

// JB: do i still need these? aggregatorName doesn't even get touched and gets overridden
// const options = {
// 	aggregatorName: STATIC.AGGREGATOR.uniqueCountOfGrandTotal,
// 	unusedOrientationCutoff: Infinity,
// }

const props = defineProps(
  {
    uid: {
      type: String,
      required: true,
    },
  }
)

const dataset = ref([])
const activeRenderer = ref(STATIC.RENDERER.table)

onMounted(async () => {
  try {
    const data = await getData(props?.uid)
    dataset.value = data
  } catch (error) {
    console.log('Something went wrong retrieving the data from the endpoint :: ', error)
  }
})
</script>

<template>
  <section className="pivot-table">
    <PivotTableUI
      :data="dataset"
      :renderers="{
        ...TSVRenderer,
        ...createPlotlyRenderer(Plotly, {}),
        ...createChartjsRenderer(Bar, { palette }),
      }"
      :cols="['Party Size']"
      :rows="['Payer Gender']"
      :rendererName="activeRenderer"
    />
    <!-- v-bind="options" -->
  </section>
</template>

<style>
@import '../../data-explorer.react/src/app.css';
</style>
