// packages/@react/components/renderers/PlotlyRenderer.jsx
import React from 'react'
import PropTypes from 'prop-types'
import PivotData from '../../../@core/js/PivotData'

/* eslint-disable react/prop-types */
// eslint can't see inherited propTypes!

function makeRenderer(
  PlotlyComponent,
  traceOptions = {},
  layoutOptions = {},
  transpose = false
) {
  class Renderer extends React.PureComponent {
    render() {
      const pivotData = new PivotData(this.props)
      const rowKeys = pivotData.getRowKeys()
      const colKeys = pivotData.getColKeys()

      const traceKeys = transpose ? colKeys : rowKeys
      if (traceKeys.length === 0) {
        traceKeys.push([]);
      }

      const datumKeys = transpose ? rowKeys : colKeys
      if (datumKeys.length === 0) {
        datumKeys.push([]);
      }

      let fullAggName = this.props.aggregatorName;
      const numInputs = this.props.aggregators[fullAggName]([])().numInputs || 0
      if (numInputs !== 0) {
        fullAggName += ` of ${this.props.vals.slice(0, numInputs).join(', ')}`
      }

      const data = traceKeys.map(traceKey => {
        const values = []
        const labels = []

        for (const datumKey of datumKeys) {
          const val = parseFloat(
            pivotData
              .getAggregator(
                transpose ? datumKey : traceKey,
                transpose ? traceKey : datumKey
              )
              .value()
          )

          values.push(isFinite(val) ? val : null)
          labels.push(datumKey.join('-') || ' ')
        }

        const trace = {name: traceKey.join('-') || fullAggName}
        if (traceOptions.type === 'pie') {
          trace.values = values
          trace.labels = labels.length > 1 ? labels : [fullAggName]
        }
        else {
          trace.x = transpose ? values : labels
          trace.y = transpose ? labels : values
        }

        return Object.assign(trace, traceOptions)
      })

      let titleText = fullAggName
      const hAxisTitle = transpose
        ? this.props.rows.join('-')
        : this.props.cols.join('-')
      
      const groupByTitle = transpose
        ? this.props.cols.join('-')
        : this.props.rows.join('-')
      
      if (hAxisTitle !== '') {
        titleText += ` vs ${hAxisTitle}`;
      }

      if (groupByTitle !== '') {
        titleText += ` by ${groupByTitle}`;
      }

      const layout = {
        title: titleText,
        hovermode: 'closest',
        /* eslint-disable no-magic-numbers */
        width: window.innerWidth / 1.5,
        height: window.innerHeight / 1.4 - 50,
        /* eslint-enable no-magic-numbers */
      }

      if (traceOptions.type === 'pie') {
        const columns = Math.ceil(Math.sqrt(data.length));
        const rows = Math.ceil(data.length / columns);
        layout.grid = {columns, rows};
        data.forEach((d, i) => {
          d.domain = {
            row: Math.floor(i / columns),
            column: i - columns * Math.floor(i / columns),
          };
          if (data.length > 1) {
            d.title = d.name;
          }
        })

        if (data[0].labels.length === 1) {
          layout.showlegend = false;
        }
      } else {
        layout.xaxis = {
          title: transpose ? fullAggName : null,
          automargin: true,
        };
        layout.yaxis = {
          title: transpose ? null : fullAggName,
          automargin: true,
        };
      }

      return (
        <div>
          <PlotlyComponent
            data={data}
            layout={Object.assign(
              layout,
              layoutOptions,
              this.props.plotlyOptions
            )}
            config={this.props.plotlyConfig}
            onUpdate={this.props.onRendererUpdate}
          />
        </div>
      )
    }
  }

  Renderer.defaultProps = Object.assign({}, PivotData.defaultProps, {
    plotlyOptions: {},
    plotlyConfig: {},
  })

  Renderer.propTypes = Object.assign({}, PivotData.propTypes, {
    plotlyOptions: PropTypes.object,
    plotlyConfig: PropTypes.object,
    onRendererUpdate: PropTypes.func,
  })

  return Renderer;
}

function makeScatterRenderer(PlotlyComponent) {
  class Renderer extends React.PureComponent {
    render() {
      const pivotData = new PivotData(this.props);
      const rowKeys = pivotData.getRowKeys();
      const colKeys = pivotData.getColKeys();
      if (rowKeys.length === 0) {
        rowKeys.push([]);
      }
      if (colKeys.length === 0) {
        colKeys.push([]);
      }

      const data = {x: [], y: [], text: [], type: 'scatter', mode: 'markers'};

      rowKeys.map(rowKey => {
        colKeys.map(colKey => {
          const v = pivotData.getAggregator(rowKey, colKey).value();
          if (v !== null) {
            data.x.push(colKey.join('-'));
            data.y.push(rowKey.join('-'));
            data.text.push(v);
          }
        });
      });

      const layout = {
        title: this.props.rows.join('-') + ' vs ' + this.props.cols.join('-'),
        hovermode: 'closest',
        /* eslint-disable no-magic-numbers */
        xaxis: {title: this.props.cols.join('-'), automargin: true},
        yaxis: {title: this.props.rows.join('-'), automargin: true},
        width: window.innerWidth / 1.5,
        height: window.innerHeight / 1.4 - 50,
        /* eslint-enable no-magic-numbers */
      };

      return (
        <PlotlyComponent
          data={[data]}
          layout={Object.assign(layout, this.props.plotlyOptions)}
          config={this.props.plotlyConfig}
          onUpdate={this.props.onRendererUpdate}
        />
      );
    }
  }

  Renderer.defaultProps = Object.assign({}, PivotData.defaultProps, {
    plotlyOptions: {},
    plotlyConfig: {},
  });
  Renderer.propTypes = Object.assign({}, PivotData.propTypes, {
    plotlyOptions: PropTypes.object,
    plotlyConfig: PropTypes.object,
    onRendererUpdate: PropTypes.func,
  });

  return Renderer;
}

export default function createPlotlyRenderer(PlotlyComponent) {
  return {
    'Grouped Column Chart': makeRenderer(
      PlotlyComponent,
      {type: 'bar'},
      {barmode: 'group'}
    ),

    'Stacked Column Chart': makeRenderer(
      PlotlyComponent,
      {type: 'bar'},
      {barmode: 'relative'}
    ),

    'Grouped Bar Chart': makeRenderer(
      PlotlyComponent,
      {type: 'bar', orientation: 'h'},
      {barmode: 'group'},
      true
    ),

    'Stacked Bar Chart': makeRenderer(
      PlotlyComponent,
      {type: 'bar', orientation: 'h'},
      {barmode: 'relative'},
      true
    ),

    'Line Chart': makeRenderer(PlotlyComponent),
    'Dot Chart': makeRenderer(PlotlyComponent, {mode: 'markers'}, {}, true),
    'Area Chart': makeRenderer(PlotlyComponent, {stackgroup: 1}),
    'Scatter Chart': makeScatterRenderer(PlotlyComponent),

    'Multiple Pie Chart': makeRenderer(
      PlotlyComponent,
      {type: 'pie', scalegroup: 1, hoverinfo: 'label+value', textinfo: 'none'},
      {},
      true
    ),
  }
}

// packages/@vue/components/renderers/PlotlyRenderer.jsx
import { defineComponent, ref } from 'vue'
import PivotData from '../../../@core/js/PivotData'

const dataPlotly = [
  {
    type: 'bar',
    name: 'Dataset 1',
    x: [100, 200, 300, 400, 500, 600, 700],
    y: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
    orientation: 'h',
    marker: {
      color: 'rgb(255, 99, 132)',
      opacity: 0.5,
    },
  },
  {
    type: 'bar',
    name: 'Dataset 2',
    x: [200, 300, 400, 500, 600, 700, 800],
    y: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
    orientation: 'h',
    marker: {
      color: 'rgb(53, 162, 235)',
      opacity: 0.5,
    },
  },
]

const layoutPlotly = {
  // width: 320,
  // height: 240,
  barmode: 'group',
  title: {text: 'A Fancy Plot'},
}

function makeRenderer(
  PlotlyComponent,
  traceOptions = {},
  layoutOptions = {},
  transpose = false,
) {
  return defineComponent({
    name: 'PlotlyRenderer',

    props: {
      // JB: there are defaults in PivotData.defaultProps that should be transferred, however also duplication.
      aggregators: Object,
      cols: Array,
      rows: Array,
      vals: Array,
      aggregatorName: String,
      sorters: Object,
      valueFilter: Object,
      rowOrder: String,
      colOrder: String,
      derivedAttributes: Object,

      data: Array,
    },
    
    setup(props) {
      console.log('JB :props: ', props)
      
      const pivotData = ref(new PivotData(props))

      const rowKeys = ref(pivotData.value.getRowKeys()) // => answers
      const colKeys = ref(pivotData.value.getColKeys()) // => breakdown; insights

      const traceKeys = transpose ? colKeys.value : rowKeys.value
      if (traceKeys.length === 0) {
        traceKeys.push([])
      }

      const datumKeys = transpose ? rowKeys.value : colKeys.value
      if (datumKeys.length === 0) {
        datumKeys.push([])
      }

      let fullAggName = props.aggregatorName;
      const numInputs = props.aggregators[fullAggName]([])().numInputs || 0
      if (numInputs !== 0) {
        fullAggName += ` of ${props.vals.slice(0, numInputs).join(', ')}`
      }

      const data = traceKeys.map(traceKey => {
        const values = []
        const labels = []

        for (const datumKey of datumKeys) {
          const val = parseFloat(
            pivotData.value
              .getAggregator(
                transpose ? datumKey : traceKey,
                transpose ? traceKey : datumKey
              )
              .value()
          )

          values.push(isFinite(val) ? val : null)
          labels.push(datumKey.join('-') || ' ')
        }

        const trace = {name: traceKey.join('-') || fullAggName}
        if (traceOptions.type === 'pie') {
          trace.values = values
          trace.labels = labels.length > 1 ? labels : [fullAggName]
        }
        else {
          trace.x = transpose ? values : labels
          trace.y = transpose ? labels : values
        }

        return Object.assign(trace, traceOptions)
      })

      let titleText = fullAggName
      const hAxisTitle = transpose
        ? this.props.rows.join('-')
        : this.props.cols.join('-')
      
      const groupByTitle = transpose
        ? this.props.cols.join('-')
        : this.props.rows.join('-')
      
      if (hAxisTitle !== '') {
        titleText += ` vs ${hAxisTitle}`
      }

      if (groupByTitle !== '') {
        titleText += ` by ${groupByTitle}`
      }

      const layout = {
        title: titleText,
        hovermode: 'closest',
        /* eslint-disable no-magic-numbers */
        width: window.innerWidth / 1.5,
        height: window.innerHeight / 1.4 - 50,
        /* eslint-enable no-magic-numbers */
      }

      return { data, layout }
    },

    render() {
      return (
        <>
          <div>Plotly Renderer (to be implemented)</div>
          <PlotlyComponent
            data={data}
            layout={layoutPlotly}
          />
        </>
      )
    }
  })
}

export default function createPlotlyRenderer(PlotlyComponent, config) {
  return {
    Plotly: makeRenderer(PlotlyComponent, {type: 'bar'}, {barmode: 'group'}),
  }
}
