// packages/@vue/components/renderers/TableRenderer.vue
<script setup lang="js">
import PivotData from '../../../@core/js/PivotData'
import { redColorScaleGenerator, spanSize } from '../../../@core/js/ui'

const STATICS = {
  heatmapMode: {
    full: 'full',
    column: 'col',
    row: 'row',
  }
}

const props = defineProps({
  data: Array,
})

const pivotData = new PivotData(props)

const rowKeys = pivotData.getRowKeys()
const colKeys = pivotData.getColKeys()
const rowAttrs = pivotData.props.rows
const colAttrs = pivotData.props.cols

const grandTotalAggregator = pivotData.getAggregator([], [])

let valueCellColors = () => {}
let rowTotalColors = () => {}
let colTotalColors = () => {}

// JB: can not implement this functionality with out converting to render function + jsx
// if (config.heatmapMode) {}

const getClickHandler =
  props.tableOptions && props.tableOptions.clickCallback
    ? (value, rowValues, colValues) => {
        const filters = {}

        for (const i of Object.keys(colAttrs || {})) {
          const attr = colAttrs[i]
          if (colValues[i] !== null) {
            filters[attr] = colValues[i]
          }
        }

        for (const i of Object.keys(rowAttrs || {})) {
          const attr = rowAttrs[i]
          if (rowValues[i] !== null) {
            filters[attr] = rowValues[i]
          }
        }

        return e =>
          props.tableOptions.clickCallback(
            e,
            value,
            filters,
            pivotData
          )
      }
    : null
</script>

<template>
  <div class="border-red-500 border-2 p-2">
    <h1 class="text-red-500">Table Renderer</h1>
    
    <!-- <code class="text-xs">{{ props.data }}</code> -->

    <table className="pvtTable">
      <thead>
        <tr v-for="item in colAttrs" :key="`colAttr${j}`">

          <!-- AI: auto generated/implied from React version; probably broken -->
          <th v-if="item && j === 0" :rowspan="colAttrs.length" :colspan="rowAttrs.length" class="pvtAxisLabel"></th>
          <th v-for="(colKey, i) in colKeys" :key="`colKey${i}`" :colspan="spanSize(colKeys, i, j)" v-if="colKey[j] !== (colKeys[i - 1] && colKeys[i - 1][j])" class="pvtColLabel">
            {{ colKey[j] || 'Total' }}
          </th>
          <th v-if="j === 0" rowspan="2" class="pvtTotalLabel">Total</th>
        </tr>
      </thead>

      <tbody>
        <!-- AI: auto generated/implied from React version; probably broken -->
        <tr v-for="(rowKey, i) in rowKeys" :key="`rowKey${i}`">
          <th v-for="(r, j) in rowKey" :key="`rowAttr${j}`" v-if="r !== (rowKey[j - 1] && rowKey[j - 1])" :rowspan="spanSize(rowKeys, i, j)" class="pvtRowLabel">
            {{ r || 'Total' }}
          </th>

          <td v-for="(colKey, k) in colKeys" :key="`valueCell${k}`" class="pvtVal">
            {{
              pivotData
                .getAggregator(rowKey, colKey)
                .value()
            }}
          </td>

          <td class="pvtTotal">
            {{
              pivotData
                .getAggregator(rowKey, [])
                .value()
            }}
          </td>
        </tr>

        <tr>
          <th class="pvtTotalLabel">Total</th>
          <td v-for="(colKey, k) in colKeys" :key="`colTotal${k}`" class="pvtTotal">
            {{
              pivotData
                .getAggregator([], colKey)
                .value()
            }}
          </td>
          <td class="pvtGrandTotal">
            {{ grandTotalAggregator.value() }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style>
@import '../../../@react/components/renderers/tableRenderer.css';
</style>

// packages/@react/components/renderers/TableRenderer.jsx
import React from 'react'
import PropTypes from 'prop-types'
import PivotData from '../../../@core/js/PivotData'
import { redColorScaleGenerator, spanSize } from '../../../@core/js/ui.ts'

import './tableRenderer.css'

const STATICS = {
  heatmapMode: {
    full: 'full',
    column: 'col',
    row: 'row',
  }
}

function makeRenderer(
  config = {}
) {
  class TableRenderer extends React.PureComponent {
    render() {
      const pivotData = new PivotData(this.props)

      const rowKeys = pivotData.getRowKeys()
      const colKeys = pivotData.getColKeys()
      const rowAttrs = pivotData.props.rows
      const colAttrs = pivotData.props.cols
      
      const grandTotalAggregator = pivotData.getAggregator([], [])

      let valueCellColors = () => {}
      let rowTotalColors = () => {}
      let colTotalColors = () => {}

      if (config.heatmapMode) {
        const colorScaleGenerator = this.props.tableColorScaleGenerator
        
        const rowTotalValues = colKeys.map(x =>
          pivotData.getAggregator([], x).value()
        )

        rowTotalColors = colorScaleGenerator(rowTotalValues)
        
        const colTotalValues = rowKeys.map(x =>
          pivotData.getAggregator(x, []).value()
        )
        
        colTotalColors = colorScaleGenerator(colTotalValues)

        if (config.heatmapMode === STATICS.heatmapMode.full) {
          const allValues = []

          rowKeys.map(r =>
            colKeys.map(c =>
              allValues.push(pivotData.getAggregator(r, c).value())
            )
          )

          const colorScale = colorScaleGenerator(allValues)

          valueCellColors = (r, c, v) => colorScale(v)
        }
        else if (config.heatmapMode === STATICS.heatmapMode.row) {
          const rowColorScales = {}

          rowKeys.map(r => {
            const rowValues = colKeys.map(x =>
              pivotData.getAggregator(r, x).value()
            )
            rowColorScales[r] = colorScaleGenerator(rowValues)
          })

          valueCellColors = (r, c, v) => rowColorScales[r](v)
        }
        else if (config.heatmapMode === STATICS.heatmapMode.column) {
          const colColorScales = {}

          colKeys.map(c => {
            const colValues = rowKeys.map(x =>
              pivotData.getAggregator(x, c).value()
            )
            colColorScales[c] = colorScaleGenerator(colValues)
          })

          valueCellColors = (r, c, v) => colColorScales[c](v)
        }
      }

      const getClickHandler =
        this.props.tableOptions && this.props.tableOptions.clickCallback
          ? (value, rowValues, colValues) => {
              const filters = {}

              for (const i of Object.keys(colAttrs || {})) {
                const attr = colAttrs[i]
                if (colValues[i] !== null) {
                  filters[attr] = colValues[i]
                }
              }

              for (const i of Object.keys(rowAttrs || {})) {
                const attr = rowAttrs[i]
                if (rowValues[i] !== null) {
                  filters[attr] = rowValues[i]
                }
              }

              return e =>
                this.props.tableOptions.clickCallback(
                  e,
                  value,
                  filters,
                  pivotData
                )
            }
          : null

      return (
        <>
          {/* <code className="text-sm">{JSON.stringify(this.props.rows, null, 2)} {JSON.stringify(this.props.cols, null, 2)}</code> */}
          {/* <code className="text-xs">{JSON.stringify(pivotData, null, 2)}</code> */}

          <table className="pvtTable">
            <thead>
              {
                colAttrs.map(function(item, j) {
                  return (
                    <tr key={`colAttr${j}`}>
                      {j === 0 && rowAttrs.length !== 0 && (
                        <th rowSpan={colAttrs.length} colSpan={rowAttrs.length} />
                      )}

                      <th className="pvtAxisLabel">{item}</th>

                      {
                        colKeys.map(function(colKey, i) {
                          const x = spanSize(colKeys, i, j)
                          if (x === -1) {
                            return null
                          }

                          return (
                            <th
                              className="pvtColLabel"
                              key={`colKey${i}`}
                              rowSpan={
                                j === colAttrs.length - 1 && rowAttrs.length !== 0
                                  ? 2
                                  : 1
                              }
                              colSpan={x}
                            >
                              {colKey[j]}
                            </th>
                          )
                        })
                      }

                      {j === 0 && (
                        <th
                          className="pvtTotalLabel"
                          rowSpan={
                            colAttrs.length + (rowAttrs.length === 0 ? 0 : 1)
                          }
                        >
                          Totals
                        </th>
                      )}
                    </tr>
                  )
                })
              }

              {
                rowAttrs.length !== 0 && (
                  <tr>
                    {
                      rowAttrs.map(function(r, i) {
                        return (
                          <th className="pvtAxisLabel" key={`rowAttr${i}`}>
                            {r}
                          </th>
                        )
                      })
                    }
                    
                    <th className="pvtTotalLabel">
                      {colAttrs.length === 0 ? 'Totals' : null}
                    </th>
                  </tr>
                )
              }
            </thead>

            <tbody>
              {
                rowKeys.map(function(rowKey, i) {
                  const totalAggregator = pivotData.getAggregator(rowKey, [])

                  return (
                    <tr key={`rowKeyRow${i}`}>
                      {
                        rowKey.map(function(txt, j) {
                          const x = spanSize(rowKeys, i, j)

                          if (x === -1) {
                            return null
                          }

                          return (
                            <th
                              className="pvtRowLabel"
                              key={`rowKeyLabel${i}-${j}`}
                              rowSpan={x}
                              colSpan={
                                j === rowAttrs.length - 1 && colAttrs.length !== 0
                                  ? 2
                                  : 1
                              }
                            >
                              {txt}
                            </th>
                          )
                        })
                      }

                      {
                        colKeys.map(function(colKey, j) {
                          const aggregator = pivotData.getAggregator(rowKey, colKey)

                          return (
                            <td
                              className="pvtVal"
                              key={`pvtVal${i}-${j}`}
                              onClick={
                                getClickHandler &&
                                getClickHandler(aggregator.value(), rowKey, colKey)
                              }
                              style={valueCellColors(
                                rowKey,
                                colKey,
                                aggregator.value()
                              )}
                            >
                              {aggregator.format(aggregator.value())}
                            </td>
                          )
                        })
                      }

                      <td
                        className="pvtTotal"
                        onClick={
                          getClickHandler &&
                          getClickHandler(totalAggregator.value(), rowKey, [null])
                        }
                        style={colTotalColors(totalAggregator.value())}
                      >
                        {totalAggregator.format(totalAggregator.value())}
                      </td>
                    </tr>
                  )
                })
              }

              <tr>
                <th
                  className="pvtTotalLabel"
                  colSpan={rowAttrs.length + (colAttrs.length === 0 ? 0 : 1)}
                >
                  Totals
                </th>

                {
                  colKeys.map(function(colKey, i) {
                    const totalAggregator = pivotData.getAggregator([], colKey)

                    return (
                      <td
                        className="pvtTotal"
                        key={`total${i}`}
                        onClick={
                          getClickHandler &&
                          getClickHandler(totalAggregator.value(), [null], colKey)
                        }
                        style={rowTotalColors(totalAggregator.value())}
                      >
                        {totalAggregator.format(totalAggregator.value())}
                      </td>
                    )
                  })
                }

                <td
                  className="pvtGrandTotal"
                  onClick={
                    getClickHandler &&
                    getClickHandler(grandTotalAggregator.value(), [null], [null])
                  }
                >
                  {grandTotalAggregator.format(grandTotalAggregator.value())}
                </td>
              </tr>
            </tbody>
          </table>
        </>
      )
    }
  }

  TableRenderer.propTypes = {
    ...PivotData.propTypes,
    tableColorScaleGenerator: PropTypes.func,
    tableOptions: PropTypes.object,
  }
  
  TableRenderer.defaultProps = {
    ...PivotData.defaultProps,
    tableColorScaleGenerator: redColorScaleGenerator,
    tableOptions: {},
  }
  
  return TableRenderer
}

export default {
  Table: makeRenderer(),
  'Table Heatmap': makeRenderer({heatmapMode: STATICS.heatmapMode.full}),
  'Table Column Heatmap': makeRenderer({heatmapMode: STATICS.heatmapMode.column}),
  'Table Row Heatmap': makeRenderer({heatmapMode: STATICS.heatmapMode.row}),
}
