// packages/@vue/components/renderers/FoobarRenderer.jsx
import { defineComponent, computed, ref, watchEffect } from 'vue'
import PivotData from '../../../@core/js/PivotData'
import { redColorScaleGenerator, spanSize } from '../../../@core/js/ui'

import '../../../@react/components/renderers/foobarRenderer.css'

function makeRenderer(
  config = {}
) {
  const componentName = config.mode
    ? `FoobarRenderer-${config.mode}`
    : 'FoobarRenderer'
  
  return defineComponent({
    name: componentName,

    props: {
      // JB: there are defaults in PivotData.defaultProps that should be transferred, however also duplication.
      aggregators: Object,
      cols: Array,
      rows: Array,
      vals: Array,
      aggregatorName: String,
      sorters: Object,
      valueFilter: Object,
      rowOrder: String,
      colOrder: String,
      derivedAttributes: Object,

      tableColorScaleGenerator: {
        type: Function,
        default: () => redColorScaleGenerator,
      },
      tableOptions: {
        type: Object,
        default: () => ({}),
      },

      data: Array,
    },

    setup(props) {
      console.log('JB :props: ', props.data)
      const pivotData = ref(new PivotData(props))

      const rowKeys = ref()
      const colKeys = ref()
      const rowAttrs = ref()
      const colAttrs = ref()

      const grandTotalAggregator = ref(() => pivotData.value.getAggregator([], []))

      watchEffect(() => {
        pivotData.value = new PivotData(props)

        rowKeys.value = pivotData.value.getRowKeys()
        colKeys.value = pivotData.value.getColKeys()
        rowAttrs.value = pivotData.value.props.rows
        colAttrs.value = pivotData.value.props.cols

        grandTotalAggregator.value = pivotData.value.getAggregator([], [])
      })

      return {
        props,
        pivotData,
        rowKeys,
        colKeys,
        rowAttrs,
        colAttrs,
        grandTotalAggregator,
      }
    },

    render() {
      return (
        <div class="border-blue-500 border-2 p-2">
          <h1>hello foobar wtf</h1>
          {
            (config.mode === 'FOO') && (
              <h2>hello foo</h2>
            )
          }

          {
            (config.mode === 'BAR') && (
              <h2>hello bar</h2>
            )
          }

          <ol class="bg-indigo-400 list-decimal">
            {
              this.colAttrs.map((c, j) => (
                <li key={`colAttr${j}`}>{c}</li>
              ))
            }
          </ol>

          <ol class="bg-rose-400 list-decimal">
            {
              this.colKeys.map((colKey, i) => (
                <li key={`colKey${i}`}>{JSON.stringify(colKey)}</li>
              ))
            }
          </ol>
          
          <ol class="bg-green-400 list-decimal">
            {
              this.colAttrs.map((c, j) => (
                this.colKeys.map((colKey, i) => (
                  <li key={`colKey${i}`}>{colKey[j]}</li>
                ))
              ))
            }
          </ol>
          
          <hr />

          <ol class="bg-orange-400 list-decimal">
            {
              this.rowAttrs.map((r, i) => (
                <li key={`rowAttrs${i}`}>{r}</li>
              ))
            }
          </ol>

          <hr />

          <ol class="bg-blue-400 list-decimal">
            {
              this.rowKeys.map((rowKey, i) => (
                <li key={`rowKeyRow${i}`}>{JSON.stringify(rowKey)}</li>
              ))
            }
          </ol>

          <ol class="bg-violet-400 list-decimal">
            {
              this.rowKeys.map((rowKey, i) => (
                rowKey.map((txt, j) => {
                  return (
                    <li key={`rowKeyLabel${i}-${j}`}>{txt}</li>
                  )
                })
              ))
            }
          </ol>

          <ol class="bg-teal-400 list-decimal">
            {
              this.rowKeys.map((rowKey, i) => (
                this.colKeys.map((colKey, j) => {
                  const aggregator = this.pivotData.getAggregator(rowKey, colKey)

                  return (
                    <li key={`pvtVal${i}-${j}`}>{aggregator.format(aggregator.value())}</li>
                  )
                })
              ))
            }
          </ol>

          <hr />

          <ol class="bg-yellow-400 list-decimal">
            {
              this.colKeys.map((colKey, i) => {
                const totalAggregator = this.pivotData.getAggregator([], colKey)

                return (
                  <li key={`total${i}`}>{totalAggregator.format(totalAggregator.value())}</li>
                )
              })
            }
          </ol>

          <p>{this.grandTotalAggregator.format(this.grandTotalAggregator.value())}</p>

          <code class="text-xs">{JSON.stringify(this.props.data, null, 2)}</code>
        </div>
      )
    },
  })
}

export default {
  Foobar: makeRenderer(),
  Foo: makeRenderer({ mode: 'FOO'}),
  Bar: makeRenderer({ mode: 'BAR'}),
}

// src/@pix8/pivotTable/@react/components/renderers/FoobarRenderer.jsx
import React from 'react'
import PivotData from '../../../@core/js/PivotData'
// import PivotEngine from '../../../@core/js/PivotEngine'

import './foobarRenderer.css'

// JB: the proper OOP way to do it as oppose to leveraging closure, would be to extend a base class and use that to create the other modes as a superset Class. Also turning into functional component may be another option.
function makeRenderer(
  config = {}
) {
  const FoobarRenderer = (props) => {
    const pivotData = new PivotData(props)
    // const pivotEngine = new PivotEngine(props)

    const rowKeys = pivotData.getRowKeys()
    const colKeys = pivotData.getColKeys()
    const rowAttrs = pivotData.props.rows // unmodified data
    const colAttrs = pivotData.props.cols // unmodified data
    
    const grandTotalAggregator = pivotData.getAggregator([], [])

    console.log('FoobarRenderer :pivotData: ', pivotData)
    // console.log('FoobarRenderer :pivotEngine: ', pivotEngine)

    return (
      <div>
        <h1>hello foobar wtf</h1>
        {
          (config.mode === 'FOO') && (
            <h2>hello foo</h2>
          )
        }

        {
          (config.mode === 'BAR') && (
            <h2>hello bar</h2>
          )
        }

        <ol className="bg-indigo-400 list-decimal">
          {
            colAttrs.map((c, j) => (
              <li key={`colAttr${j}`}>{c}</li>
            ))
          }
        </ol>

        <ol className="bg-rose-400 list-decimal">
          {
            colKeys.map((colKey, i) => (
              <li key={`colKey${i}`}>{JSON.stringify(colKey)}</li>
            ))
          }
        </ol>
        
        <ol className="bg-green-400 list-decimal">
          {
            colAttrs.map((c, j) => (
              colKeys.map((colKey, i) => (
                <li key={`colKey${i}`}>{colKey[j]}</li>
              ))
            ))
          }
        </ol>
        
        <hr />

        <ol className="bg-orange-400 list-decimal">
          {
            rowAttrs.map((r, i) => (
              <li key={`rowAttrs${i}`}>{r}</li>
            ))
          }
        </ol>

        <hr />

        <ol className="bg-blue-400 list-decimal">
          {
            rowKeys.map((rowKey, i) => (
              <li key={`rowKeyRow${i}`}>{JSON.stringify(rowKey)}</li>
            ))
          }
        </ol>

        <ol className="bg-violet-400 list-decimal">
          {
            rowKeys.map((rowKey, i) => (
              rowKey.map((txt, j) => {
                return (
                  <li key={`rowKeyLabel${i}-${j}`}>{txt}</li>
                )
              })
            ))
          }
        </ol>

        <ol className="bg-teal-400 list-decimal">
          {
            rowKeys.map((rowKey, i) => (
              colKeys.map((colKey, j) => {
                const aggregator = pivotData.getAggregator(rowKey, colKey)

                return (
                  <li key={`pvtVal${i}-${j}`}>{aggregator.format(aggregator.value())}</li>
                )
              })
            ))
          }
        </ol>

        <hr />

        <ol className="bg-yellow-400 list-decimal">
          {
            colKeys.map((colKey, i) => {
              const totalAggregator = pivotData.getAggregator([], colKey)

              return (
                <li key={`total${i}`}>{totalAggregator.format(totalAggregator.value())}</li>
              )
            })
          }
        </ol>

        <p>{grandTotalAggregator.format(grandTotalAggregator.value())}</p>
      </div>
    )
  }
  
  FoobarRenderer.propTypes = {
    ...PivotData.propTypes,
  }
  
  FoobarRenderer.defaultProps = {
    ...PivotData.defaultProps,
  }

  return FoobarRenderer
}

export default {
  Foobar: makeRenderer(),
  Foo: makeRenderer({ mode: 'FOO'}),
  Bar: makeRenderer({ mode: 'BAR'}),
}
